name: Deploy Android App to Internal Track

on:
  push:
    branches:
      - master # Trigger deployment on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Updated to Java 17 for Android Gradle Plugin 8.13.0 compatibility
        distribution: 'temurin' # Using temurin for better compatibility
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Decode Keystore
      id: decode_keystore
      env:
        SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
      run: |
        echo $SIGNING_KEY_BASE64 | base64 --decode > ${{ github.workspace }}/app/release-keystore.jks
        echo "STORE_FILE_PATH=${{ github.workspace }}/app/release-keystore.jks" >> $GITHUB_ENV

    - name: Build Release AAB
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        ./gradlew :app:bundleRelease \
          -Pandroid.injected.signing.store.file="${{ env.STORE_FILE_PATH }}" \
          -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
          -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
          -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"

    - name: Upload AAB to Google Play (Internal Track)
      uses: r0adkll/upload-google-play@v1.1.2
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_KEY }}
        packageName: com.example.mindpairs # Updated to match your actual package name
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal
        status: completed # Set status to completed for automatic deployment
        # Optional: You can specify what percentage of users get this rollout
        # userFraction: 0.5 # Deploys to 50% of users on the track
        # Optional: Add release notes
        # whatsNewDirectory: path/to/your/release_notes/

    - name: Clean up keystore
      if: always()
      run: rm -f ${{ github.workspace }}/app/release-keystore.jks
